<a href="https://colab.research.google.com/github/boramkim0514/python01/blob/main/D20_numpy_notes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

 * numeric python
 * 수치 연산을 위한 파이썬 라이브러리

In [ ]:
# 1. numpy의 배열을 ndarray라고 합니다
, python으 list ndarray화 할 수있다
py_list =


#타입확인

In [ ]:
arange
zeros, ones, full
linespace
random.rand. random. randn. random.uniform
random.choice. random.randint
**axies**
indexing, slicing
shape, ndim
np.newaxis. np.squeeze
ravel flatten reshape broad casting 전치행결 

#np.full
#5로 채워진 다차원배열

In [3]:
np.zeros((2, 3))#딥러닝 머신러닝에서 편향(bias) 초기값

array([[0., 0., 0.],
       [0., 0., 0.]])

ㅌ

In [4]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [5]:
np.ones((2,3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [7]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

#점구간 만들기
##, 시각화에서 선을 그을 용도로 보통 사용

In [8]:

np.linspace

<function numpy.linspace>

In [10]:
np.linspace(1, 10, 3) # 1부터 10까지 3개의 수를 균일 구간으로 만들기

array([ 1. ,  5.5, 10. ])

In [11]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [12]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

#Random을 사용하기 위한 Numpy
랜덤배열은 ** 딥러닝** 에서 매개변수 (가중치 W, 편향 b)를 초기화 하기 위해 사용

*초기화 : 최초에 가지고 있는 값

**번외**
*__init__

생성자? : 객체 초기화 메소드, 객체를 만들기한 
클래스를 이용해서 객체를 만들 때 객체가 처음 가지고 있어야 하는 값을 세팅하는 메소드  

객체와 인스턴스 차이?
객체가 만들어지는 공간 
Heap이라는 메모리공간에 person이라는 객체가 만들어짐, 이 객체가 만들 때 이름과 나이를 넣은 것

Heap은 너무나 넓은 메모리 공간, 
객체를 찾아갈 수 있는 근거가 필요 ->> 이 객채가 어디있는지 알아야 하니까 매무리 16 2진수 메모리 주소값이 변수로 들어가서 넣어서 나온 값, 인스턴스 = 객체 

p1이 참조하고 있는 접근, 참조하고 있는 값, 
변

In [13]:
객체에 대한 이야기
##완전 랜덤 만들기
정규분포나 균등분포가 아닌 완벽한 랜덤

SyntaxError: ignored

In [14]:
np.random.rand(2,3)

array([[0.0113619 , 0.5865853 , 0.2737183 ],
       [0.69893039, 0.74737437, 0.27972801]])

In [15]:
np.random.randn(16) #이런 값이 중요하지 않음 분포, 빈도, 양이 중요함 그래서 시각화가 중요!


array([-1.40806338,  1.01860594,  0.39387772,  1.61900537,  0.75533382,
       -0.17646859, -0.76659284,  0.06950062,  2.07519992, -0.40944537,
        1.04992552,  0.80854953, -1.23687428, -0.61080044, -0.10803701,
        0.05087828])

#정규분포 랜덤 : 
값의 빈도가 평균이 제일 많고, 최대 최소 갈수록 작아지는 형태

데칼코마니 제일 딱 가운데 값 50%, median 값=mean

(완전)정규분포 일때 미디언과 평균이 같음

y축 구간별 값의 빈도수
x축 구간?

정규분포 랜덤은 딥러닝의 매개변수 초기밧으로 사용 




## 균등분포 랜덤
값의 분포가 값의 구간이 다 똑같음, 
아주가끔 사용됨 타이밍, 사비에르 등 방법이 있음,
구간 값이 필요함 

In [16]:
np.random.uniform(1.0, 3.0, size = (3,4))

array([[1.13115478, 1.56805961, 1.67845368, 2.62942954],
       [2.81731684, 1.40366505, 2.87761767, 1.37217682],
       [1.01770523, 2.3296312 , 1.17366963, 1.33654146]])

## 정수 랜덤 샘플링
* 'np.random.choice'
* 샘플링 : 전체(모분포) 일부 표본(일부)를 추출하는 행위
* 딥러닝에서 (파이썬)mini-batch를 만들 때 사용



In [17]:
np.random.choice(10, size=(2, 3) ) #0-9에서의 정수(배열 내에서도 랜덤 추출이 가능함) 중 랜덤하게 2, 3 배열로 추출하는 방법, 기본은 중복추출, 중복을 제거하는 방법도 존재

array([[9, 3, 3],
       [2, 5, 2]])

In [18]:
arr = np.arange(1,6) #1-5까지 데이터
np.random.choice(arr, size=(2,3))

array([[3, 1, 5],
       [1, 2, 1]])

In [19]:
#비중복 추출
np.random.choice(arr, size=(2, 2), replace=False)

array([[4, 2],
       [1, 5]])

In [20]:
np.random.choice(arr, size=(2, 2), replace=False)

array([[5, 2],
       [1, 4]])

In [21]:
np.random.choice(arr, size=(2, 3), replace=False) 

ValueError: ignored

##랜덤 정수 배열 만들기
'np.random.randint


In [30]:
arr1 = np.random.randint(1, 100, size=(5,))
arr1

array([76, 92,  2, 75, 53])

In [34]:
arr2 = np.random.randint(1, 100, size=(5, 1))
arr2

array([[96],
       [84],
       [16],
       [95],
       [98]])

##다차원배열 관련
notion 2.1 데이터와 행렬 참고
배열 형태, 형상인가 모델 만드는 방법
베열에 대한 이해 꼭 필요!



#데이터의 종류
## 스칼라 - scalar
* 어떠한 실수 $x$라고 정의합니다. 
 ''' python
    height = 180.1
    age = 34.3
'''
* 'height , age'를 스칼라라고 함. 단순한 특정한 (상수)값 => 0차원 데이터

* 




## 벡터 
* 실수값 $x$ 가 모여져 있는 것
'''python
    heights =[180.1, 175.5, 163.3]
'''
** heights란 백터 생성한 것
** 벡터란 스칼라를 모은 것 0차원 scalar를 모은 것 => 1차원 배열
    모아진 데이터의 개수가 'N'개 라면 ** N차원 백터라고 함
    열(column)벡터를 기본으로 한다. 
    행의 모양을 하지만 열백터임



In [37]:
# 2.1 데이터와 numpy를 이용한 벡터표현
heights_1 = np.array([180.1, 175.5, 163.3])
heights_1 

array([180.1, 175.5, 163.3])

In [41]:
heights_2 = np.array([[180.1],
                     [175.5], 
                     [163.3]])
heights_2

array([[180.1],
       [175.5],
       [163.3]])

##싸이킷런, 텐섶플로우 같은 머신러닝 프레임에서는 무조건 2차원 배열로 받는다
    *열백터이지만 

    결론, 
    heights 1 과 heights2는 배열로서 같지 않지만
    heights1 1차원열, heights2는 2차원 배열
    둘은 같은 벡터
    *, 행벡터의 모양을 하고 이쓰나 실제 학적으로 '열백터'. 

    *heights2는 열의 수가 1개인 열백터 모양을 하고있음

    대부분 머신러닝 라이브러리는 기본적인 데이터 취급을 열백터로 하기 때문에 2차원 배열 이상부터 시작한다 
    열백터가 기본!!




In [ ]:
#모든 데이터의 기준은 백터

#모든 데이터의 기준은 백터, 
과학 물리 모든 값들이 모여져 있음, 
물리는 방향성이 모은 것

* 미분

## 행렬 matrix
* 2 차원 배열
1차원 배열인 벡터가 여러개 모인 것, 


## 텐서 
3차원 이상의 배열 의미
3차원 배열(3차원 텐서) 2차원 배열이 모여있다 

4차원 배열(4차원 텐서)는 3차원 배열이 모여잇다
M'차월 배열, 그냥 텐서

텐서 개념 활용 모든 배열의 모양 이야기 가능

* 0 랭크

#### 3랭크 텐서 이미지 

tensorflow 구글 제공하는 딥러닝 프로엠워크
배열을 흘린다(flow)..

미리 흘릴 네트워크(신경망) 배열(데이터)를 준비하고 거기에 배열(데이터)을 흘린다.

네트워크를 설계/구조화 해서 데이터를 흘려보내는 개념



In [ ]:
#축이란? 데이터가 추가되는 방향의 인덱스
#배열의 모양 인식이 목표

# axis 는 데이터가 꽤어지는 이유, 왜 이런 결과가 나오는지  이해가 중요!

인덱스 슬라이팅

In [43]:
arr= np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [50]:
arr[(1:3 ,1:3)]

SyntaxError: ignored

In [54]:
arr[ : , 1 : 3]

array([[[ 4,  5,  6],
        [ 7,  8,  9]],

       [[16, 17, 18],
        [19, 20, 21]],

       [[28, 29, 30],
        [31, 32, 33]]])

In [53]:
arr[ : , 1 : 3, 1:]

array([[[ 5,  6],
        [ 8,  9]],

       [[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

# spread 연산자

In [57]:
arr = np.arange(36).reshape(2, 3, 3, 2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [58]:
arr[0, : , : , 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [62]:
arr[0, ... , 0] #spread 연산자 #이미지 처리 할때 함 이런게 있다 정도 -> 외워야함?! 

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

# 보통 이미지 데이터를 딥러닝에서 사용하고자 하면

4차원 배열 형태로 감
N 이미지 갯수
H 세로 픽셀
W 가로 픽셀
C 컬러 RGB GRAYSCALE :1)
# 훈련에 사용할 이미지 형상(shape) 확인 : 6000 개 26 세로픽셀, 28 가로 픽셀 , 1그레이스케일
스프레드 연산자 (28, 28)
images = [ 600000, ... , 
[0.1111

#차원수 확장 개념
 원하는 차원 위치에 'np.newaxis 추가

matplot lib 흑백이미지 표시

arr[0, ... , 0] 
# images

spread 

####진짜 이미지 데이터 다루는 방법 배우게 될 예정! 오호 ㅎㅎㅎ 재밌겠군! 신기하다!
####필터링으로 이미합성


numpy np.newazis 
tensorflow



#차원 쥐어짜기
    np.squeeze 
    개수가 1인 차원의 내용을 없애는 기법
    (1, 28, 28, 1) 데이터를 모으기 위해 배열을 만드는 건데 1개씩만 있어서 쓸모없으니 없앤다?

    temp_squeeze = np.squeeze(temp_arr)
    temp_squeeze.shape 

# 평탄화 
* 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것
* 'ravel' 원본 배열을 평탄화시킨 '참조'배열을 만들어냄 (view, reference)
*flatten '복사'된 배열



In [63]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [64]:
x

array([[13, 10,  2, 11, 10],
       [ 0,  7,  2,  4,  5],
       [13,  2,  1,  7,  5]])

In [65]:
#ravel
temp = np.ravel(x)
temp.shape

(15,)

In [66]:
temp

array([13, 10,  2, 11, 10,  0,  7,  2,  4,  5, 13,  2,  1,  7,  5])

In [68]:
temp[0] = 100

In [69]:
x #temp를 바꿨는데 원본이 13에서 100으로 바뀜! shallow copy 개념

array([[100,  10,   2,  11,  10],
       [  0,   7,   2,   4,   5],
       [ 13,   2,   1,   7,   5]])

In [ ]:
#flatten (원본 데이터 안전관리를 위해 deep copy 개념인 flatten을 많이 씀)

#메모리 종류 3가지 내부 원리만.. 
1. stack(local 변수만 들어감)
2.heap(계층, 오브젝트)
3. static/method/class 변수는 나머지

#reshape

In [ ]:
#Data 수집
스크래핑 : 한군데서
클로링:검색엔진은 다 돌아가서 주기적으로 자료 수집

1. 목표 페이지 한군데서 스크래핑(HTML/CSS, API, Selenium)로 자료수집
2. 자료저장: csv 파일화, DB(DB-MysQL, MongoDB)
실무 - 빅데이터는 hadoop(hdfs) - 
빅데이터 파이프라인 hadoop eco system(spark, hive, pig, squoop, kafka, flume )

분석
1.시각화
2.전처리(kill)
3.모델링(인공지능 머신 AI) + Flask 

