<a href="https://colab.research.google.com/github/boramkim0514/KOIPA_AI/blob/main/D42_Tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensorflow?

Tensor(다차원 배열) flow(흘려보냄)
파이썬 신경 안에 TF session 
layer을 쌓아서 계산시키는 단계
계산 내용을 미리 정해놓고, 실제 계산시 필요한 순간(훈련)에 데이터(배열)을 흘려보낸다

GPU 설정 메모리 설정 가능


In [ ]:
import numpy as np
import tensorflow as tf

#Tensor 만들기

### tf.constant()

In [ ]:
tf.constant([1, 2, 3])

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [ ]:
tf.constant([[1,2,3],[4,5,6]]) #array는 모두 list로 만드는 건가?

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
tf.constant(((1, 2, 3),
            (4, 5, 6)))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

ndarray -> Tensor

In [ ]:
arr = np.array([1, 2, 3])
tf. 

<tf.Tensor: shape=(3,), dtype=int64, numpy=array([1, 2, 3])>

# Tensor 정보 확인


In [ ]:
tensor = tf.constant([1, 2, 3])
tensor

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

**shape확인하기**

In [ ]:
tensor.shape

TensorShape([3])

**dtype 확인하기**

In [ ]:
tensor.dtype

tf.int32

Tensor를 생성하면서 dtype 정의해주기

In [ ]:
tensor = tf.constant([1, 2, 3], dtype=tf.float32)
tensor.dtype

tf.float32

In [ ]:
tensor

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

In [ ]:
tf.cast(tensor, dtype=tf.uint8)

<tf.Tensor: shape=(3,), dtype=uint8, numpy=array([1, 2, 3], dtype=uint8)>

Tensor에서 numpy 배열

In [ ]:
tensor.numpy()

array([1., 2., 3.], dtype=float32)

In [ ]:
np.array(tensor)

array([1., 2., 3.], dtype=float32)

# Tensorflow 난수 생성

* `numpy`에서의 정규분포 : `np.random.randn`
* `tensorflow`에서의 정규분포 : `tf.random.normal`

In [ ]:
tf.random.normal([3, 3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.51041335,  0.32821316,  0.23630273],
       [-2.829283  , -0.64822984,  0.39460635],
       [-0.4078111 ,  1.5680463 ,  0.4663825 ]], dtype=float32)>

In [ ]:
#r균등분포
tf.random.uniform([3,3])

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0.32514417, 0.36383665, 0.28316557],
       [0.32482564, 0.21204329, 0.95870733],
       [0.9766555 , 0.51305807, 0.3861984 ]], dtype=float32)>

#Tensorflow 배열은 수정 불가!
반드시 tensorflow의 session, variable 만 수정 가능!

In [ ]:
tensor[0] = 1 # 불가능

TypeError: ignored