<a href="https://colab.research.google.com/github/boramkim0514/python01/blob/main/day19.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#정규표현식

In [2]:
b = 'ttt \t hhh \n yyy'

In [3]:
b

'ttt \t hhh \n yyy'

In [5]:
b = r'ttt \t hhh \n yyy'
print(b)

ttt \t hhh \n yyy


In [6]:
b = 'ttt \t hhh \n yyy'
print(b) #\t \n 제어문

ttt 	 hhh 
 yyy


In [9]:
b = 'ttt \\t hhh \\n yyy'
print(b) #\t \n 제어문

ttt \t hhh \n yyy


In [10]:
import re 
p = re.compile(r'(010|011|018)-{0,1}\d{4}--{0,1}\d{4}', re.VERBOSE)
p.match('019-2323-3434')

In [ ]:
for i in range(3):
    my_str = input(' Enter String(영문자+숫자만 입력) : ')
    p = re.compile('[a-zA-Z0-9]+')
    #m = p.match(my_str)
    p=re.compile('\w+')
    if m: 
        print('매칭 됨:',  m.group())
    else:
        print('매칭 안  됨',  my_str)

In [42]:
%%html
<marquee style='width: 100%; color: white; ' ><b>
    하나님은 어떤 분이신가  </b><marquee>

##결측치 NA null, 

In [44]:
from numpy import nan as NA
import pandas as pd
import numpy as np

In [33]:
d = pd.Series([1, NA , 6.3, NA, 9])

In [34]:
d

0    1.0
1    NaN
2    6.3
3    NaN
4    9.0
dtype: float64

In [35]:
d[d.notnull()]

0    1.0
2    6.3
4    9.0
dtype: float64

In [36]:
d[d.isnull()]

1   NaN
3   NaN
dtype: float64

In [37]:
dd = d.dropna() #null 값은 없애도  dd로 넣어주기

In [38]:
dd

0    1.0
2    6.3
4    9.0
dtype: float64

In [40]:
d #d는 변함없음

0    1.0
1    NaN
2    6.3
3    NaN
4    9.0
dtype: float64

In [41]:
d.fillna(55) #nul 값을 55로 채우기

0     1.0
1    55.0
2     6.3
3    55.0
4     9.0
dtype: float64

In [49]:
b = np.arange(1000, 13000, 1000).reshape(4,3)

In [50]:
b

array([[ 1000,  2000,  3000],
       [ 4000,  5000,  6000],
       [ 7000,  8000,  9000],
       [10000, 11000, 12000]])

In [51]:
b[3]

array([10000, 11000, 12000])

In [53]:
b[2:, 0]  #1차원 배열

array([ 7000, 10000])

In [54]:
b[2:, 0:1]  #2차원

array([[ 7000],
       [10000]])

AttributeError: ignored

In [59]:
a =np.arange(10, 121, 10).reshape(3,4)

In [60]:
a

array([[ 10,  20,  30,  40],
       [ 50,  60,  70,  80],
       [ 90, 100, 110, 120]])

In [61]:
a[1:3, 1:3]

array([[ 60,  70],
       [100, 110]])

In [62]:
a[1]

array([50, 60, 70, 80])

HTTPError: ignored