<a href="https://colab.research.google.com/github/boramkim0514/python01/blob/main/day12_pm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [5]:
n1 = np.random.randint(0,100,10) #numpy 1차원

In [6]:
n1

array([89, 69, 64, 83, 73, 32, 44, 98, 66, 65])

In [7]:
n1.shape

(10,)

In [8]:
n1.ndim #dimension  

1

In [9]:
n1.size #갯수   

10

In [10]:
n1.nbytes #8byte/item size

80

In [11]:
n1.itemsize #하나의 크기

8

In [12]:
n = n1.copy()

In [13]:
n[0:10]

array([89, 69, 64, 83, 73, 32, 44, 98, 66, 65])

In [14]:
n[0:10:2]

array([89, 64, 73, 44, 66])

In [15]:
n[0:10:3]

array([89, 83, 44, 65])

In [16]:
n[::-1]

array([65, 66, 98, 44, 32, 73, 83, 64, 69, 89])

In [17]:
n[::-2]

array([65, 98, 32, 83, 69])

In [18]:
n1

array([89, 69, 64, 83, 73, 32, 44, 98, 66, 65])

In [20]:
n.reshape(2,5)

array([[89, 69, 64, 83, 73],
       [32, 44, 98, 66, 65]])

In [21]:
n.reshape(5,2)

array([[89, 69],
       [64, 83],
       [73, 32],
       [44, 98],
       [66, 65]])

In [ ]:
n.reshape(3,3) #Error       

In [25]:
n.sort()

In [26]:
n1

array([89, 69, 64, 83, 73, 32, 44, 98, 66, 65])

In [ ]:
n1.sort(axis=1) #Error  

In [ ]:
n1.sort(descending=False) #Error

In [30]:
n1.sort?

In [38]:
n2 = np.random.randint(1, 100, 12)

In [39]:
n2

array([25, 38, 80, 31, 33, 81, 17, 42, 60, 42, 82, 84])

In [40]:
n2.reshape(3, 4)

array([[25, 38, 80, 31],
       [33, 81, 17, 42],
       [60, 42, 82, 84]])

In [41]:
n2.reshape(2,6)

array([[25, 38, 80, 31, 33, 81],
       [17, 42, 60, 42, 82, 84]])

In [45]:
n2.reshape(3,4)

array([[25, 38, 80, 31],
       [33, 81, 17, 42],
       [60, 42, 82, 84]])

In [47]:
n21 = np.arange(1, 17, dtype=np.int16)

In [48]:
n21

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16],
      dtype=int16)

In [49]:
n = n21.reshape(4,4)

In [50]:
n

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [51]:
n[:]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [52]:
n[ : , : ] #n[행, 열: ]

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]], dtype=int16)

In [56]:
n[0,3]

4

In [57]:
n[0:2]

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int16)

In [58]:
n[0:2, 1:3]

array([[2, 3],
       [6, 7]], dtype=int16)

In [67]:
n[1:4, 2:4]

array([[ 7,  8],
       [11, 12],
       [15, 16]], dtype=int16)

In [68]:
a = [2, 3, 5]

In [ ]:
a+4 #Error

In [ ]:
a == 5 #error

In [71]:
S = 0

In [73]:
for i in a:
    S = S+1
    return S

In [74]:
n[2:4, 1:3]

array([[10, 11],
       [14, 15]], dtype=int16)

In [75]:
n[2:4, 1:3]*3

array([[30, 33],
       [42, 45]], dtype=int16)

In [76]:
n[2:4, 1:3] == 0

array([[False, False],
       [False, False]])

In [77]:
n[0]

array([1, 2, 3, 4], dtype=int16)

In [78]:
n[0]<5 #행만 비교

array([ True,  True,  True,  True])

In [80]:
n[0][0] == 100 #점만 비교   

False

In [81]:
n > 10  #w전체비교

array([[False, False, False, False],
       [False, False, False, False],
       [False, False,  True,  True],
       [ True,  True,  True,  True]])

In [85]:
n[:, 0:1]

array([[ 1],
       [ 5],
       [ 9],
       [13]], dtype=int16)

In [86]:
n[:, 0:1] 

array([[ 1],
       [ 5],
       [ 9],
       [13]], dtype=int16)

In [88]:
n[0][3] *11

44

In [126]:
n[:, 3:4]

array([[100],
       [100],
       [100],
       [100]], dtype=int16)

In [128]:
n[:, 2:3]

array([[ 3],
       [ 7],
       [11],
       [15]], dtype=int16)

In [93]:
n[:, -1] = 100 #공부할 떄 암기보다 반복해서 숙달(익숙)해지는것이 중요 

In [97]:
n[:]

array([[  1,   2,   3, 100],
       [  5,   6,   7, 100],
       [  9,  10,  11, 100],
       [ 13,  14,  15, 100]], dtype=int16)

In [101]:
n[0].sum()

106

In [104]:
n[0].max()

100

In [108]:
n.max(axis = 1)

array([100, 100, 100, 100], dtype=int16)

In [109]:
n.max(axis =0)

array([ 13,  14,  15, 100], dtype=int16)

In [110]:
n.min(axis =0)

array([  1,   2,   3, 100], dtype=int16)

In [111]:
n.sum(axis=0)

array([ 28,  32,  36, 400])

In [113]:
n.mean(axis=0)

array([  7.,   8.,   9., 100.])

In [115]:
n.std(axis=1)

array([42.44113571, 40.70933554, 38.97755765, 37.24580513])

In [120]:
np.median(n)

10.5

In [125]:
np.median(n)

10.5

In [129]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [131]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [132]:
np.tri(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [134]:
np.empty(6)

array([4.65257021e-310, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000])

In [135]:
np.zeros((2,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [136]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [137]:
np.array([4, 5, 6, 7])

array([4, 5, 6, 7])

In [138]:
n7 = np.array([4, 5, 6, 7])

In [139]:
n7.nbytes

32

In [140]:
n7.itemsize

8

In [142]:
n8 = np.array([4, 5, 6, 7], np.int32)

In [143]:
n8.nbytes

16

In [144]:
k = [i for i in range(5, 51, 5)]

In [145]:
type(k)

list

In [146]:
k

[5, 10, 15, 20, 25, 30, 35, 40, 45, 50]

In [147]:
t = (i for i in range(10, 101, 10))

In [148]:
type(t)

generator

In [150]:
n10 = np.array(k)

In [152]:
n10

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [156]:
n11= np.array(t)

In [158]:
n11

array(<generator object <genexpr> at 0x7fd8488e0ad0>, dtype=object)

In [206]:
np?

In [ ]:

n12 = np.array(k).shape[2,5] #error

In [168]:
s1 = pd.Series([2, 4, 6, 8])

In [170]:
s1

0    2
1    4
2    6
3    8
dtype: int64

In [171]:
type(s1)

pandas.core.series.Series

In [172]:
s1.shape

(4,)

In [174]:
s1.ndim

1

In [175]:
s1.nbytes

32

In [176]:
s1.items

<bound method Series.items of 0    2
1    4
2    6
3    8
dtype: int64>

In [177]:
s1.index

RangeIndex(start=0, stop=4, step=1)

In [178]:
s1 #좌측은 index값, 우측은 값 #무시적 

0    2
1    4
2    6
3    8
dtype: int64

In [181]:
s1.index=[['T', 'K', 'B', 'Q']] #명시적 인덱스 지시

In [182]:
s1

T    2
K    4
B    6
Q    8
dtype: int64

In [191]:
s1.index=[['류현진', '강정호', '추신수', '이승엽']]

In [189]:
s1[0]

2

In [187]:
s1[0]

2

In [188]:
s1[0]

2

In [190]:
s1['강정호']

강정호    4
dtype: int64

In [192]:
s1

류현진    2
강정호    4
추신수    6
이승엽    8
dtype: int64

In [194]:
s1.iloc[1]

4

In [197]:
s1.loc?

In [199]:
s1.iloc? #i loc integer location

In [200]:
s1.iloc[1]

4

In [203]:
s1.loc['추신수']

추신수    6
dtype: int64

In [208]:
#seires 는 index & value가 있음
#dataframe 에도 index & value 가 있지 않나?! 

In [209]:
pd1 = pd.read_csv('/content/sample_data/california_housing_test.csv')

In [210]:
pd1

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [211]:
type(pd1)

pandas.core.frame.DataFrame

In [212]:
pd1.shape

(3000, 9)

In [214]:
p = pd1.copy()

In [215]:
p

longitude  latitude  ...  median_income  median_house_value
0       -122.05     37.37  ...         6.6085            344700.0
1       -118.30     34.26  ...         3.5990            176500.0
2       -117.81     33.78  ...         5.7934            270500.0
3       -118.36     33.82  ...         6.1359            330000.0
4       -119.67     36.33  ...         2.9375             81700.0
...         ...       ...  ...            ...                 ...
2995    -119.86     34.42  ...         1.1790            225000.0
2996    -118.14     34.06  ...         3.3906            237200.0
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3000 rows x 9 columns]

In [216]:
p.head(3) #head 

longitude  latitude  ...  median_income  median_house_value
0    -122.05     37.37  ...         6.6085            344700.0
1    -118.30     34.26  ...         3.5990            176500.0
2    -117.81     33.78  ...         5.7934            270500.0

[3 rows x 9 columns]

In [217]:
p.tail(3) #tail 

longitude  latitude  ...  median_income  median_house_value
2997    -119.70     36.30  ...         2.2895             62000.0
2998    -117.12     34.10  ...         3.2708            162500.0
2999    -119.63     34.42  ...         8.5608            500001.0

[3 rows x 9 columns]

In [220]:
pd2 = pd.read_csv('/content/sample_data/sc.csv') #encoding=cp949 code page 

In [221]:
pd2

이순신  85  87  90
0  강감찬  75  80  95
1  한석봉  99  98  99
2  황진이  35  45  20
3  안중근  90  85  90
4  박문수  95  98  96
5  임꺽정  15  35  45
6  김정호  90  95  80
7  정몽주  90  90  95
8  김보람  95  99  98

In [222]:
p = pd2.copy()

In [226]:
pd2 = pd.read_csv('/content/sample_data/sc.csv', header=None) #index 값 대신 묵시적 번호로 지정해주기 header=None

In [227]:
pd2

0   1   2   3
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  김보람  95  99  98

In [253]:
pd2.columns=['이름', '국어', '영어', '수학'] #pd2.colums=

In [251]:
pd2

이름  국어  영어  수학
0  이순신  85  87  90
1  강감찬  75  80  95
2  한석봉  99  98  99
3  황진이  35  45  20
4  안중근  90  85  90
5  박문수  95  98  96
6  임꺽정  15  35  45
7  김정호  90  95  80
8  정몽주  90  90  95
9  김보람  95  99  98

In [230]:
p.shape

(9, 4)

In [231]:
type(p)

pandas.core.frame.DataFrame

In [232]:
p.ndim

2

In [233]:
p.size

36

In [236]:
p.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   이순신     9 non-null      object
 1   85      9 non-null      int64 
 2   87      9 non-null      int64 
 3   90      9 non-null      int64 
dtypes: int64(3), object(1)
memory usage: 416.0+ bytes


In [241]:
p.items

<bound method DataFrame.items of    이순신  85  87  90
0  강감찬  75  80  95
1  한석봉  99  98  99
2  황진이  35  45  20
3  안중근  90  85  90
4  박문수  95  98  96
5  임꺽정  15  35  45
6  김정호  90  95  80
7  정몽주  90  90  95
8  김보람  95  99  98>

In [254]:
p.describe()

85         87         90
count   9.000000   9.000000   9.000000
mean   76.000000  80.555556  79.777778
std    30.087373  23.995370  28.097054
min    15.000000  35.000000  20.000000
25%    75.000000  80.000000  80.000000
50%    90.000000  90.000000  95.000000
75%    95.000000  98.000000  96.000000
max    99.000000  99.000000  99.000000

p.index

In [261]:
p.columns

Index(['이름', '국어', '영어', '수학'], dtype='object')

In [262]:
p['총점'] = p['국어'] + p['영어'] + p['수학']

In [264]:
p['평균'] = p['총점'] /3


In [265]:
p

이름  국어  영어  수학   총점         평균
0  이순신  85  87  90  262  87.333333
1  강감찬  75  80  95  250  83.333333
2  한석봉  99  98  99  296  98.666667
3  황진이  35  45  20  100  33.333333
4  안중근  90  85  90  265  88.333333
5  박문수  95  98  96  289  96.333333
6  임꺽정  15  35  45   95  31.666667
7  김정호  90  95  80  265  88.333333
8  정몽주  90  90  95  275  91.666667
9  김보람  95  99  98  292  97.333333

In [270]:
p.iloc[ : ,1:3]

국어  영어
0  85  87
1  75  80
2  99  98
3  35  45
4  90  85
5  95  98
6  15  35
7  90  95
8  90  90
9  95  99

In [273]:
p.iloc[ : ,1:3].sum() #sum 총점 구하기

국어    769
영어    812
dtype: int64

#수학점수 70 이상인 사람

In [275]:
p[:]

이름  국어  영어  수학   총점         평균
0  이순신  85  87  90  262  87.333333
1  강감찬  75  80  95  250  83.333333
2  한석봉  99  98  99  296  98.666667
3  황진이  35  45  20  100  33.333333
4  안중근  90  85  90  265  88.333333
5  박문수  95  98  96  289  96.333333
6  임꺽정  15  35  45   95  31.666667
7  김정호  90  95  80  265  88.333333
8  정몽주  90  90  95  275  91.666667
9  김보람  95  99  98  292  97.333333

In [ ]:
p[3,0] #error

In [281]:
p.iloc[3][0] # iloc 

'황진이'

In [ ]:
p.[3],[0]

In [282]:
p.iloc[3,0]

'황진이'

In [283]:
p['이름']

0    이순신
1    강감찬
2    한석봉
3    황진이
4    안중근
5    박문수
6    임꺽정
7    김정호
8    정몽주
9    김보람
Name: 이름, dtype: object

In [ ]:
p.loc[['이름']]

In [ ]:
p.iloc[['이름']]

In [290]:
p.loc[:, ['이름']] #p.loc[ 행 :, 컬럼제어 ['이름']]

이름
0  이순신
1  강감찬
2  한석봉
3  황진이
4  안중근
5  박문수
6  임꺽정
7  김정호
8  정몽주
9  김보람

In [294]:
p[ : ,  :  ] #왜????

SyntaxError: ignored

In [299]:
p.[ 4:6, ['국어',['영어']] #??

SyntaxError: ignored

In [300]:
p['국어'] >= 70

0     True
1     True
2     True
3    False
4     True
5     True
6    False
7     True
8     True
9     True
Name: 국어, dtype: bool

In [305]:
p.iloc[:, 1:] >= 70 #합격 불합격 맞출때 

국어     영어     수학    총점     평균
0   True   True   True  True   True
1   True   True   True  True   True
2   True   True   True  True   True
3  False  False  False  True  False
4   True   True   True  True   True
5   True   True   True  True   True
6  False  False  False  True  False
7   True   True   True  True   True
8   True   True   True  True   True
9   True   True   True  True   True

In [309]:
p['영어'] <= 60

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7    False
8    False
9    False
Name: 영어, dtype: bool

In [316]:
p.iloc[:, 1:] >= 70 #integer location

국어     영어     수학    총점     평균
0   True   True   True  True   True
1   True   True   True  True   True
2   True   True   True  True   True
3  False  False  False  True  False
4   True   True   True  True   True
5   True   True   True  True   True
6  False  False  False  True  False
7   True   True   True  True   True
8   True   True   True  True   True
9   True   True   True  True   True

In [315]:
p.loc[ :, ['국어', '영어', '수학']] >= 70

국어     영어     수학
0   True   True   True
1   True   True   True
2   True   True   True
3  False  False  False
4   True   True   True
5   True   True   True
6  False  False  False
7   True   True   True
8   True   True   True
9   True   True   True

In [313]:
p?

In [314]:
p.iloc?

In [317]:
p.sum()

이름    이순신강감찬한석봉황진이안중근박문수임꺽정김정호정몽주김보람
국어                               769
영어                               812
수학                               808
총점                              2389
평균                           796.333
dtype: object

In [318]:
p.mean()

국어     76.900000
영어     81.200000
수학     80.800000
총점    238.900000
평균     79.633333
dtype: float64

In [320]:
p.sum(axis=1)

0    611.333333
1    583.333333
2    690.666667
3    233.333333
4    618.333333
5    674.333333
6    221.666667
7    618.333333
8    641.666667
9    681.333333
dtype: float64

In [321]:
p['국어'].value_counts()

90    3
95    2
75    1
15    1
85    1
99    1
35    1
Name: 국어, dtype: int64

In [322]:
p['국어'].value_counts(ascending=False)

90    3
95    2
75    1
15    1
85    1
99    1
35    1
Name: 국어, dtype: int64

In [323]:
p['국어'].sort_values()

6    15
3    35
1    75
0    85
4    90
7    90
8    90
5    95
9    95
2    99
Name: 국어, dtype: int64

In [324]:
p['국어'].sort_values(ascending=False)

2    99
9    95
5    95
8    90
7    90
4    90
0    85
1    75
3    35
6    15
Name: 국어, dtype: int64

In [325]:
p.sort_values(by='영어')

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
2  한석봉  99  98  99  296  98.666667
5  박문수  95  98  96  289  96.333333
9  김보람  95  99  98  292  97.333333

In [326]:
p.sort_values(by=['영어', '수학'])

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667
9  김보람  95  99  98  292  97.333333

In [327]:
p

이름  국어  영어  수학   총점         평균
0  이순신  85  87  90  262  87.333333
1  강감찬  75  80  95  250  83.333333
2  한석봉  99  98  99  296  98.666667
3  황진이  35  45  20  100  33.333333
4  안중근  90  85  90  265  88.333333
5  박문수  95  98  96  289  96.333333
6  임꺽정  15  35  45   95  31.666667
7  김정호  90  95  80  265  88.333333
8  정몽주  90  90  95  275  91.666667
9  김보람  95  99  98  292  97.333333

In [328]:
p.sort_values(by=['영어', '수학'], inplace=True)

In [329]:
p

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667
9  김보람  95  99  98  292  97.333333

In [334]:
p['영어']+5

6     40
3     50
1     85
4     90
0     92
8     95
7    100
5    103
2    103
9    104
Name: 영어, dtype: int64

In [336]:
p

이름  국어  영어  수학   총점         평균
6  임꺽정  15  35  45   95  31.666667
3  황진이  35  45  20  100  33.333333
1  강감찬  75  80  95  250  83.333333
4  안중근  90  85  90  265  88.333333
0  이순신  85  87  90  262  87.333333
8  정몽주  90  90  95  275  91.666667
7  김정호  90  95  80  265  88.333333
5  박문수  95  98  96  289  96.333333
2  한석봉  99  98  99  296  98.666667
9  김보람  95  99  98  292  97.333333

In [361]:
def get_grade(x):
    grade = ''
    if x >= 90: grade = '수'
    elif x >= 80: grade = '우'
    elif x >= 70: grade = '미'
    elif x >= 60: grade = '양'
    else: grade = '가'
    return grade

In [363]:
p['평가'] = p['평균'].apply(lambda x: get_grade(x))

In [364]:
p

이름  국어  영어  수학   총점         평균 평가
6  임꺽정  15  35  45   95  31.666667  가
3  황진이  35  45  20  100  33.333333  가
1  강감찬  75  80  95  250  83.333333  우
4  안중근  90  85  90  265  88.333333  우
0  이순신  85  87  90  262  87.333333  우
8  정몽주  90  90  95  275  91.666667  수
7  김정호  90  95  80  265  88.333333  우
5  박문수  95  98  96  289  96.333333  수
2  한석봉  99  98  99  296  98.666667  수
9  김보람  95  99  98  292  97.333333  수