<a href="https://colab.research.google.com/github/boramkim0514/python01/blob/main/day11_5_18_21_pm.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
import pandas as pd

오후 수업 numpy & pandas 학습정리


In [213]:
np11 = np.array([2, 4, 6, 2], dtype=np.int32)
np12 = np.array([3, 6, 9, 12, 15], dtype=np.int16)

In [163]:
np11.shape

(4,)

In [109]:
np11 +=5

In [214]:
np11.size #item 갯수

4

In [215]:
np11.nbytes #총 바이트 수

16

In [216]:
np11.itemsize

4

In [ ]:
np12.shape

In [185]:
np13 = np.arange(1,11)

In [186]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [187]:
np13 * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [24]:
np13[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
np13[3:7] #index /slicing 

array([4, 5, 6, 7])

In [29]:
np13[3:7]+5

array([ 9, 10, 11, 12])

In [30]:
np13

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
np13 = np13[3:7] + 5

In [32]:
np13

array([ 9, 10, 11, 12])

In [33]:
np14 = np.arange(1, 11)

In [34]:
np14[2:5] += 3

In [35]:
np14

array([ 1,  2,  6,  7,  8,  6,  7,  8,  9, 10])

In [36]:
np15 = np14

In [37]:
np14[4] = 90

In [38]:
np14

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [39]:
np15

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [43]:
np16 = np14.copy()

In [44]:
np14

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [45]:
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [46]:
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [47]:
np14[2] = 555

In [48]:
np14

array([  1,   2, 555,   7,  90,   6,   7,   8,   9,  10])

In [49]:
np16

array([ 1,  2,  6,  7, 90,  6,  7,  8,  9, 10])

In [50]:
np14[6:]

array([ 7,  8,  9, 10])

In [51]:
np14[6:]=0

In [52]:
np14

array([  1,   2, 555,   7,  90,   6,   0,   0,   0,   0])

In [53]:
np2 = np.arange(1, 4)

In [54]:
np2

array([1, 2, 3])

In [ ]:
np2 = np.arange(a1, a2)

In [63]:
a1 = [1, 2, 3]

In [64]:
a2 = [2, 4, 6, 8, 10]

In [ ]:
np2 = np.array([a1,a2])

In [72]:
np222 = np.arange(1, 16)

In [69]:
np2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [70]:
np2.reshape(3, 5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [101]:
np2.[2, 3]

SyntaxError: ignored

In [102]:
np222

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [103]:
np222[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [76]:
np222 = np2.reshape(3,5)

In [77]:
np222

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [104]:
np222[1, 3]

9

In [80]:
np222[:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [90]:
np222[0:2]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [91]:
np222[0:2, 1:2]

array([[2],
       [7]])

In [93]:
np222[2:3]

array([[11, 12, 13, 14, 15]])

In [106]:
np222[0:3, 0:2]

array([[ 1,  2],
       [ 6,  7],
       [11, 12]])

In [105]:
np222[0:3, 0:2] +5

array([[ 6,  7],
       [11, 12],
       [16, 17]])

In [107]:
np222[0:2, 0:1]

array([[1],
       [6]])

In [108]:
np222[0:2, 0:2]

array([[1, 2],
       [6, 7]])

배열 인덱싱, 슬라이싱 p. 146, 149



In [116]:
np3 = np.arange(10, 241, 10)

In [117]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [118]:
np3.ndim # ndim 차원을 보는 것

1

In [119]:
np3

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120, 130,
       140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240])

In [120]:
np3.shape

(24,)

In [121]:
np3.reshape(2, 12) #2행 12열

array([[ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100, 110, 120],
       [130, 140, 150, 160, 170, 180, 190, 200, 210, 220, 230, 240]])

In [137]:
np33= np3.reshape(2, 3,4)

In [138]:
np333= np33.reshape(2,3,4) 

In [139]:
np33.ndim

3

In [142]:
np333.shape

(2, 3, 4)

In [143]:
np333 #60 70 을어떻게 빼내올까?

array([[[ 10,  20,  30,  40],
        [ 50,  60,  70,  80],
        [ 90, 100, 110, 120]],

       [[130, 140, 150, 160],
        [170, 180, 190, 200],
        [210, 220, 230, 240]]])

In [154]:
np4444 = np333.reshape(2, 3, 2, 2, )

In [155]:
np4444

array([[[[ 10,  20],
         [ 30,  40]],

        [[ 50,  60],
         [ 70,  80]],

        [[ 90, 100],
         [110, 120]]],


       [[[130, 140],
         [150, 160]],

        [[170, 180],
         [190, 200]],

        [[210, 220],
         [230, 240]]]])

In [156]:
np4444.ndim

4