<a href="https://colab.research.google.com/github/boramkim0514/python01/blob/main/Day20_00_numpy_%EA%B8%B0%EC%B4%88%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
import numpy as np

* numeric python
* 수치 연산을 위한 파이썬 라이브러리
  * 과학에 관련된 모듈 `scipy`
* 일반 파이썬을 이용할 때 보다 수치 연산에 관해 훨씬 빠르다.
* **배열 병렬 연산에 특화**

# 1. numpy의 배열을 ndarray라고 한다.

In [8]:
# 1. python의 list를 ndarray화 할 수 있다.
py_list = [1, 2, 3]
arr1 = np.array(py_list)
arr1

array([1, 2, 3])

In [9]:
# 타입 확인
type(arr1)

numpy.ndarray

# np.full
* 사용 빈도 낮음

In [10]:
# 5로 채워진 다차원 배열을 만들고 싶어요
np.zeros((2, 3)) # 딥러닝이나 머신러닝에서 편향(bias) 초기값

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
# 5로 채워진 배열 만들기
np.ones((2, 3)) * 5

array([[5., 5., 5.],
       [5., 5., 5.]])

In [13]:
np.full((2, 3), 5)

array([[5, 5, 5],
       [5, 5, 5]])

# 점구간 만들기
* np.linspace
* 시각화에서 선을 그을 용도로 보통 사용

In [14]:
np.linspace(1, 10, 3) # 1부터 10까지 3개의 수를 균일한 구간으로 만든다. -> 2개의 구간을 생성

array([ 1. ,  5.5, 10. ])

In [15]:
np.linspace(1, 10, 4)

array([ 1.,  4.,  7., 10.])

In [16]:
np.linspace(1, 10, 5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

# Random을 사용하기 위한 Numpy
* 랜덤 배열은 **딥러닝**에서 매개변수(`가중치 W`,`편향 b`)를 초기화 하기 위해서 사용
* 초기화 : 최초에 가지고 있는 값을 만드는 과정

**번외**
* 생성자? : 객체 초기화 메소드
  - 클래스를 이용해서 객체를 만들 때 객체가 처음 가지고 있어야 하는 값을 세팅하는 메소드

## 완전 랜덤 만들기
* `np.random.rand` : 정규 분포나 균등분포가 아닌 완벽한 랜덤

In [17]:
np.random.rand( 2, 3 )

array([[0.97652541, 0.27131899, 0.15435745],
       [0.71873665, 0.43094822, 0.79057956]])

In [18]:
np.random.rand(2, 3, 4)

array([[[0.46982977, 0.91661337, 0.0684967 , 0.41571035],
        [0.01743807, 0.22279501, 0.21497235, 0.81062624],
        [0.81287567, 0.4707799 , 0.59431814, 0.27171804]],

       [[0.97459102, 0.25467419, 0.06029769, 0.64375299],
        [0.42223235, 0.80887916, 0.85707717, 0.5084666 ],
        [0.61348158, 0.4354113 , 0.61253845, 0.2156822 ]]])

## 정규분포 랜덤
* `np.random.randn`

In [19]:
np.random.randn(16)

array([ 2.3789727 ,  0.26308476,  1.16559519, -0.47352448, -1.46524684,
        2.34336591,  0.47271605,  1.23433884,  0.30926479, -0.89626076,
        0.98124565, -0.20981904,  0.05544566,  0.14488608, -0.59220569,
        0.42147656])

정규 분포 랜덤은 딥러닝의 매개변수 초깃값으로 사용된다.

In [20]:
np.random.randn(2, 3, 4)

array([[[ 0.22854749,  0.07345862, -0.8926444 ,  0.01958414],
        [-0.19390461,  1.65425552, -0.08383847,  0.38309272],
        [ 0.19031556,  0.03620123,  0.28716091,  0.56221034]],

       [[ 1.08685556, -0.27428934,  0.92895336, -0.05820996],
        [ 0.32002237, -1.21761203, -0.25218237,  0.52163549],
        [ 0.92562523, -0.08809244, -0.57262467, -0.53025339]]])

## 균등분포 랜덤
* `np.random.uniform`

In [21]:
np.random.uniform(1.0, 3.0, size=(3, 4) )

array([[2.90201393, 2.57980483, 1.64169418, 1.50719508],
       [1.22495614, 2.02598084, 1.3854291 , 1.71186578],
       [1.40728344, 2.10612774, 1.52917765, 1.93308528]])

## 정수 랜덤 샘플링
* `np.random.choice`
* 샘플링 : 전체에서 일부를 추출하는 행위
* 딥러닝에서는 `mini-batch`를 만들 때 사용

In [22]:
# 0 ~ 9까지의 정수를 랜덤하게 (2, 3) 배열 형태로 추출
np.random.choice(10, size=(2, 3))

array([[0, 8, 1],
       [3, 3, 5]])

In [23]:
# 배열 내에서도 랜덤 추출이 가능
arr = np.arange(1, 6)

np.random.choice(arr, size=(2, 2))

array([[2, 3],
       [5, 1]])

In [24]:
# 중복 추출 x - replace 옵션을 alse 주면 중복 추출 x
np.random.choice(arr, size=(2, 2), replace=False)

array([[1, 2],
       [5, 4]])

## 랜덤 정수 배열 만들기
* `np.random.randint`

In [25]:
arr1 = np.random.randint(1, 100, size=(5, ))
arr1

array([ 5,  4, 11, 91, 75])

In [26]:
arr2 = np.random.randint(1, 100, size=(5, 1))
arr2

array([[42],
       [51],
       [95],
       [81],
       [46]])

# 다차원 배열에 대한 이야기
* notion에 자세히 설명 되어 있어요
  * 2.1 데이터와 행렬 참고하세요

## 스칼라 - scalar

* 어떠한 실수값 $x$라고 정의합니다.
  ```python
    height = 180.1
    age = 34.3
  ```
  * `height, age`를 스칼라라고 합니다.
  * 0차원 데이터

## 벡터 - vector
* 실수값 $x$가 모여져 있는 것
  ```python
    heights=[180.1, 175.5, 163.3]
  ```
  * `heights`라는 벡터를 생성한 것
  * `scalar`를 모은 것
  * 1차원 배열
  * 모아진 데이터의 개수가 `N`개라면 **N차원 벡터**라고 한다.
  * 열벡터를 기본으로 한다.

In [27]:
# 행벡터의 모양을 하고 있지만, 1차원 배열이기 때문에 열벡터로 따져야 한다.
heights_1 = np.array([180.1, 175.5, 163.3])
heights_1 

array([180.1, 175.5, 163.3])

In [28]:
heights_2 = np.array([[180.1],
                      [175.5],
                      [163.3]])
heights_2

array([[180.1],
       [175.5],
       [163.3]])

In [29]:
heights_1.shape, heights_2.shape

((3,), (3, 1))

$$
heights\_1 \in R^3
$$

$$
heights\_2 \in R^{3\times1} =  R^{3}
$$

사이킷런, 텐서플로우 같은 머신러닝 프레임워크에서는 무조건 2차원 배열로 데이터를 받는다.

* 열벡터의 모양을 띄고 있거나
* 2차원이상의 배열을 사용해야 한다.

사람의 키 정보를 3개를 모았어요
```python
heights = [1,2,3] # 오류
heights = [[1],[2],[3]] # 허용
```

heights1과 heights2는 같은 배열일까요? `No`
  * heights1은 1차원 배열, heights2는 2차원 배열

heights1과 heights2는 같은 벡터일까요? `Yes`
  * heights1은 numpy에서는 행벡터의 모양을 하고 있지만 실제 수학적으로는 `열벡터`이다.
  * heights2는 열의 수가 1개인 열벡터의 모양을 하고 있다.

대부분의 머신러닝 라이브러리는 기본적인 데이터의 취급을 **열벡터**로 하기 때문에 2차원 배열 이상부터 취급한다.

## 행렬 - matrix
* 2차원 배열
* 1차원 배열인 벡터가 여러개 모여 있는 것
  * ```python
      person_info = [[180.1, 33, 80.5],
                      [175.1, 32, 77.3]]
    ```

## 텐서 - tensor
* 3차원 이상의 배열을 의미한다.
* 3차원 배열(3차원 텐서)은 2차원 배열이 모여있다.
* 4차원 배열(4차원 텐서)은 3차원 배열이 모여있다.
* `N차원 배열`을 그냥 텐서라고 한다.
  * `N`이 꼭 3부터는 아니에요...
* 텐서의 개념을 활용하면 모든 배열의 모양을 이야기 할 수 있다.
  * `0 Rank Tensor` - 스칼라
  * `1 Rank Tensor` - 벡터
  * `2 Rank Tensor` - 행렬
  * `3 Rank Tensor` - 3랭크 텐서...
* Tensorflow는 뭘까요...?
  * 구글에서 제공하는 딥러닝 프레임워크
  * Tensor를 흘린다(flow)
  * 미리 흘릴 네트워크를 준비하고 거기에 배열(데이터)을 흘린다.

# axis 이해하기
axis : 축. 축이란? 데이터가 추가되는 방향의 **인덱스**

예를 들어서 3차원 (3, 4, 5)
* 3차원 배열에 추가되는건 2차원 배열 -> axis=0
* 2차원 배열에 추가되는건 1차원 배열 -> axis=1
* 1차원 배열에 추가되는건 0차원 스칼라 -> axis=2

In [30]:
arr = np.arange(1, 37).reshape(3, 4, 3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [31]:
np.max(arr, axis=0)

array([[25, 26, 27],
       [28, 29, 30],
       [31, 32, 33],
       [34, 35, 36]])

In [32]:
arr = np.random.randint(1, 37, size=(3,4,3))
arr

array([[[19,  1, 33],
        [ 6, 34, 29],
        [ 8,  1, 17],
        [15,  5, 14]],

       [[ 8, 10, 29],
        [ 7, 35, 18],
        [22, 21, 33],
        [35, 36,  2]],

       [[23,  2, 11],
        [ 4, 31, 24],
        [23, 10,  6],
        [12, 12, 12]]])

In [33]:
np.max(arr, axis=2)

array([[33, 34, 17, 15],
       [29, 35, 33, 36],
       [23, 31, 23, 12]])

In [34]:
arr = np.random.randint(1, 37, size=(3,3,3,3))
arr

array([[[[18, 23, 31],
         [26, 22, 35],
         [29, 11, 29]],

        [[ 5, 33, 10],
         [13, 17,  8],
         [22, 12, 35]],

        [[33, 19, 25],
         [ 7, 17, 32],
         [13, 33, 13]]],


       [[[27, 29, 14],
         [ 6, 15, 12],
         [22, 29, 20]],

        [[ 1, 29, 32],
         [32,  8, 28],
         [33, 20, 25]],

        [[ 4, 11, 31],
         [17, 19,  6],
         [10, 32, 23]]],


       [[[ 1,  6, 16],
         [20, 18, 11],
         [25, 27, 10]],

        [[ 2, 26,  8],
         [33,  6, 11],
         [22, 17, 34]],

        [[23, 32, 14],
         [32, 15, 31],
         [24, 16,  7]]]])

In [35]:
np.max(arr, axis=0)

array([[[27, 29, 31],
        [26, 22, 35],
        [29, 29, 29]],

       [[ 5, 33, 32],
        [33, 17, 28],
        [33, 20, 35]],

       [[33, 32, 31],
        [32, 19, 32],
        [24, 33, 23]]])

In [36]:
# 스칼라에는 axis가 있을까? x
# 1차원 배열에는 axis가 몇개이라요? 1개 -> axis=0 밖에 없음

a = np.arange(5) # 1차원 배열에는 스칼라만 추가 되니까...
a

array([0, 1, 2, 3, 4])

In [37]:
np.max(a, axis=0) # OK

4

In [38]:
a = np.random.randint(6, size=(2, 3)) # 2차원 배열
a

array([[1, 1, 4],
       [1, 3, 5]])

* a는 2차원 배열임
* a에서 어떤 데이터가 늘어나나요? -> 1차원 배열이 늘어나죠 -> axis=0
* a[???] -> 2차원 배열인 a에서 1차원 배열을 선택을 한거죠 -> 1차원 배열에서 스칼라가 늘어나는 방향 -> axis=1 

In [39]:
np.max(a, axis=0) # 1차원 배열이 추가되는 방향

array([1, 3, 5])

In [40]:
a = np.arange(36).reshape(3,4,3)
a

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]],

       [[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]],

       [[24, 25, 26],
        [27, 28, 29],
        [30, 31, 32],
        [33, 34, 35]]])

# 슬라이싱

In [41]:
arr = np.arange(1, 37).reshape(3,4,3)
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18],
        [19, 20, 21],
        [22, 23, 24]],

       [[25, 26, 27],
        [28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]]])

In [42]:
arr[ : , 1:3, 1:]

array([[[ 5,  6],
        [ 8,  9]],

       [[17, 18],
        [20, 21]],

       [[29, 30],
        [32, 33]]])

spread 연산자

In [43]:
arr = np.arange(36).reshape(2, 3, 3, 2)
arr

array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15],
         [16, 17]]],


       [[[18, 19],
         [20, 21],
         [22, 23]],

        [[24, 25],
         [26, 27],
         [28, 29]],

        [[30, 31],
         [32, 33],
         [34, 35]]]])

In [44]:
arr[0, :, :, 0]

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

In [45]:
arr[0, ..., 0] # spread 연산자

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16]])

이런게 있다 정도만 보고 넘어가세요

보통 이미지 데이터를 딥러닝에서 사용하고자 하면 : `(N, H, W, C)`
* `N` : 이미지의 개수
* `H` : 세로 픽셀의 개수
* `W` : 가로 픽셀의 개수
* `C` : 채널수(컬러 RGB : 3, GRAYSCALE : 1)

In [46]:
# 훈련에 사용할 이미지의 형상(shape)을 확인 : (60000, 28, 28, 1)
# matplotlib에서 흑백 이미지를 표시하고 싶으면 (28, 28)
# images = [60000, 28, 28, 1] -> images[0, ..., 0] -> (28, 28)

# 차원 추가( 차원수 확장 )
* 흑백 이미지를 가져 왔는데 형상이 `(28, 28)`
* 딥러닝에서 이미지를 다루고자 하면 `(N,H,W,C)`를 유지 해야 한다.
* `(28, 28)` -> `(1, 28, 28, 1)`로 만들어야 딥러닝에서 다룰 수가 있다.
* 원하는 차원 위치에 `np.newaxis`를 추가하면 된다.
  * numpy : `np.newaxis`
  * tensorflow : `tf.newaxis`

In [47]:
arr = np.random.rand(28, 28)
arr.shape

(28, 28)

`(28, 28)`형식의 배열은 `(H, W)` 정보만 존재하는 상태 -> `(1, 28, 28, 1)` 형태로 만들어 줘야 이미지 분석(CNN)을 할 수 있다.

In [48]:
temp_arr = arr[np.newaxis, :, :, np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

In [49]:
temp_arr = arr[np.newaxis, ..., np.newaxis]
temp_arr.shape

(1, 28, 28, 1)

# 차원 쥐어 짜기
* `np.squeeze`
* 개수가 1인 차원의 내용을 없애는 기법

In [50]:
temp_arr.shape

(1, 28, 28, 1)

In [51]:
temp_squeeze = np.squeeze(temp_arr)
temp_squeeze.shape

(28, 28)

# 평탄화
* 2차원 이상의 배열을 1차원 배열로 평평하게 펴주는 것 (★★★★★)
  * `ravel` : 원본 배열을 평탄화 시킨 **참조**배열을 만들어 낸다. (View 또는 Reference라고 한다.)
  * `flatten` : 원본 배열을 평탄화 시킨 **복사된**배열을 만들어 낸다.

`ravel`은 원본 배열에 수정이 가해질 가능성이 있고, `flatten`은 원본 배열에 영향을 미치지 않는다.

In [52]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [53]:
x

array([[ 8,  0,  5,  5, 13],
       [ 7,  7,  9,  4, 14],
       [11, 13,  4,  0,  6]])

## ravel

In [54]:
temp = np.ravel(x)
temp.shape

(15,)

In [55]:
temp

array([ 8,  0,  5,  5, 13,  7,  7,  9,  4, 14, 11, 13,  4,  0,  6])

In [56]:
temp[0] = 100
temp

array([100,   0,   5,   5,  13,   7,   7,   9,   4,  14,  11,  13,   4,
         0,   6])

In [57]:
x

array([[100,   0,   5,   5,  13],
       [  7,   7,   9,   4,  14],
       [ 11,  13,   4,   0,   6]])

In [58]:
x[1][3] = 50000
temp

array([  100,     0,     5,     5,    13,     7,     7,     9, 50000,
          14,    11,    13,     4,     0,     6])

## flatten

In [59]:
x = np.random.randint(15, size=(3, 5))
x.shape

(3, 5)

In [60]:
temp_flatten = x.flatten()
temp_flatten.shape

(15,)

In [61]:
temp_flatten[0] = 100
temp_flatten

array([100,  12,   7,   3,   9,   0,  12,  12,  10,   9,   3,   2,   3,
         8,  13])

In [62]:
x

array([[ 6, 12,  7,  3,  9],
       [ 0, 12, 12, 10,  9],
       [ 3,  2,  3,  8, 13]])

원본 데이터를 안전하게 관리할 수 있기 때문에 ravel보다 flatten을 많이 사용해요

# reshape
배열의 형상을 재구성하는 것

In [63]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [64]:
x.reshape(2, 10)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [65]:
x.reshape(4, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [66]:
x.reshape(5, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

reshape 팁 : reshape 함수 내의 모든 숫자를 곱했을 때 스칼라 원소의 개수와 같으면 된다.

In [67]:
x.reshape(2, 5, 2) # 가능

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

reshape의 -1은 조커

In [68]:
x.reshape(2, -1, 2)

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13],
        [14, 15],
        [16, 17],
        [18, 19]]])

In [70]:
x.reshape(2, -1, -1)

ValueError: ignored

`(60000, 28, 28, 1)` -> `(60000, ?)`

In [ ]:
arr = np.random.randn(60000, 28, 28, 3)
arr.shape

In [ ]:
arr1 = arr.reshape(60000, -1, 3)
arr1.shape

In [ ]:
# 코드 리펙터링
IMAGE_SIZE = arr.shape[0]
IMAGE_CH   = arr.shape[-1]

arr.reshape(IMAGE_SIZE, -1 ,IMAGE_CH).shape

# 브로드캐스팅
* 차원 수가 다른 배열끼리 연산
* 차원이 달라도 0차원 스칼라의 개수가 똑같으면 연산이 가능
* 저차원 배열을 고차원 배열로 확장
  * 수학적으로 따지게 되면 고차원 배열의 shape과 똑같이 생긴 1벡터(np.ones)를 만들어서 저차원 배열과 곱한 배열을 만들어서 계산


In [ ]:
x = np.arange(20).reshape(4, 5)
y = np.arange(20, 40).reshape(4, 5)

x.shape, y.shape

In [ ]:
x + y

In [ ]:
x * y

브로드 캐스팅은 저차원을 고차원으로 임시로 늘려주는 것

In [ ]:
x + 2

# shape이 다를 때의 연산

In [ ]:
a = np.arange(12).reshape(4, 3)  # (4, 3)
b = np.arange(100, 103)          # (3, )
c = np.arange(1000, 1004)        # (4, )
d = b.reshape(1, 3)              # (1, 3)
e = np.arange(0, 4).reshape(4, 1)# (4, 1)

In [ ]:
a + b

In [ ]:
a + c

In [ ]:
a = np.arange(12).reshape(4, 3)  # (4, 3)
a

In [ ]:
a

In [71]:
a = np.arange(12).reshape(4, 3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [73]:
b = np.arange(100, 103)  
b

array([100, 101, 102])